server:
  servlet:
    context-path: /auto
  port: 9999

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api_runner?useSSL=false
    username: root
    password: root

logging:
  level:
    root: info
    com.auto.core: trace